### ISSUE TITLE
Architecture using Lambda, CW, S3 and CF

### ISSUE THREAD

**Issue by strogonoff** [relaton/api.relaton.org#22]
It is possible to have an architecture like follows:

* trigger a Lambda function once every X seconds using CloudWatch

* in Lambda:
  * fetch document sources
  * build bibliography index
  * upload to S3 bucket

* cache that S3 bucket behind CF
* serve index in static form. Cheap and fast!

Unknowns:

This works as is for querying references by exact ID (e.g., `ISO 10241-1:2011, 6.4`). If we need to support more vague queries, we might have to implement another Lambda function.

cc @ronaldtse suggested to tag @abunashir

**Comment by ronaldtse** [comment]
Yes this is possible for *some* bibliographic data. 

There are two types of bibliographic data  Relaton handles:

* ones that we have explicit approval to distribute or are free to distribute: IETF, NIST, OGC, CalConnect, ITU
  * amongst these, there are some we can get the full collection from one endpoint. These are IETF, NIST, OGC and CalConnect. 
  * the rest we do not have a single endpoint and have to scrape — this means we cannot know the full library of contents and cannot refresh them all the time. 

* ones that we do not have explicit consent and we can only keep them as a user cache: ISO, IEC, GB. These we can only fetch / update when a user fetches them. We also cannot distribute these as HTML. 

In implementation we must take into consideration of the categories above.

**Comment by ronaldtse** [comment]
There is some confusion on how Relaton fetch works. The following clarifies how things work:

For all data that we can have full source, we store on GH:
- local: We fetch from our GH copy
- API: As part of the API system, a lambda will sync S3 with GH so that there is no delay in fetching the record from GH (AWS to GH requires crossing providers).

For data that we cannot have full source (ISO, IEC, DOI, etc):
- local: we have to fetch from remote and store locally
- API: we have to store on S3 on the API system

**Comment by abunashir** [comment]
@andrew2net: since you are working the most with the API lately, is it something you can take over?

**Comment by andrew2net** [comment]
@abunashir yes, I'm working on it right now. I believe we can close this issue.
